version: '3'
services:
  mongodb:
    build: ./mongo
    container_name: mongodb
    volumes:
      - ./mongo/data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=monkey
    ports:
      - '27031:27017'
    command: mongod

  redis:
    image: redis:7.0.8
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - ./redis/data:/data

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - 9000:9000
      - 9002:9002
    volumes:
      - ./storage/.minio/data:/export
      - ./storage/.minio/config:/root/.minio
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
      - MINIO_CONSOLE_PORT_NUMBER=9002
    command: server /export --console-address ":9002"

  createbuckets:
    image: minio/mc
    container_name: minioconfig
    volumes:
      - ./storage/default.png:/default.png
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add monkeystorage http://minio:9000 admin password;
      /usr/bin/mc mb monkeystorage/monkey/products;
      /usr/bin/mc mb monkeystorage/monkey/users;
      /usr/bin/mc mb monkeystorage/documents;
      /usr/bin/mc anonymous set public monkeystorage/monkey/;
      /usr/bin/mc anonymous set private monkeystorage/documents/;
      /usr/bin/mc cp default.png monkeystorage/monkey/users/;
      exec sleep inf;
      "

  backend:
    build: backend/
    container_name: backend
    depends_on:
      - mongodb
      - redis
    environment:
      MONGODB_URI: mongodb://monkeyadmin:password@mongodb:27017/monkey
      MINIO_URI: http://minio:9000
      MINIO_USER: admin
      MINIO_PASSWORD: password
      REDIS_URL: redis://redis:6379
      NODE_ENV: production
      JWT_ACCESS_PRIVATE_KEY: ${JWT_ACCESS_PRIVATE_KEY} # your_private_key_base64_encoded
      JWT_ACCESS_PUBLIC_KEY: ${JWT_ACCESS_PUBLIC_KEY} # your_public_key_base64_encoded
      SMTP_USER: ${SMTP_USER} # your_gmail_account@gmail.com
      SMTP_PASSWORD: ${SMTP_PASSWORD} # your_app_password
      FRONTEND_URL: http://localhost
    ports:
      - 4000:5000

  frontend:
    build:
      context: frontend/
      args:
        GRAPHQL_URI: http://localhost:4000/v1/api
        MINIO_URI: http://localhost:9000/
        MAPS_API_KEY: ${MAPS_API_KEY} #your_google_maps_api_key
    container_name: frontend
    depends_on:
      - backend
      - minio
    ports:
      - 80:5000
